import { Providers } from './providers';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="h-full" lang="en">
      <body className="h-full m-0 p-0">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
